#TRMSim-WSN scenario
#Sun Mar 29 18:27:17 CEST 2026
simulation.numExecutions=100
recommendedTrustModel=BTRM_WSN
network.radioRange=0.12
displayName=Custom BTRM_WSN Scenario
network.probRelay=0.05
description=Imported custom scenario saved from the current simulator configuration.
network.maxNumSensors=50
network.dynamic=false
network.oscillating=false
network.collusion=false
simulation.numNetworks=100
network.probMalicious=0.7
network.probClients=0.15
id=custom-btrm-wsn
network.minNumSensors=50
