#TRMSim-WSN scenario
#Sun Mar 29 18:13:54 CEST 2026
simulation.numExecutions=50
recommendedTrustModel=BTRM_WSN
network.radioRange=0.38
displayName=Custom BTRM_WSN Scenario
network.probRelay=0.55
description=joo
network.maxNumSensors=114
network.dynamic=true
network.oscillating=false
network.collusion=false
simulation.numNetworks=10
network.probMalicious=0.1
network.probClients=0.15
id=custom-btrm-wsn
network.minNumSensors=114
