/**
 *  "TRMSim-WSN, Trust and Reputation Models Simulator for Wireless
 * Sensor Networks" is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version always keeping
 * the additional terms specified in this license.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 *
 * Additional Terms of this License
 * --------------------------------
 *
 * 1. It is Required the preservation of specified reasonable legal notices
 *   and author attributions in that material and in the Appropriate Legal
 *   Notices displayed by works containing it.
 *
 * 2. It is limited the use for publicity purposes of names of licensors or
 *   authors of the material.
 *
 * 3. It is Required indemnification of licensors and authors of that material
 *   by anyone who conveys the material (or modified versions of it) with
 *   contractual assumptions of liability to the recipient, for any liability
 *   that these contractual assumptions directly impose on those licensors
 *   and authors.
 *
 * 4. It is Prohibited misrepresentation of the origin of that material, and it is
 *   required that modified versions of such material be marked in reasonable
 *   ways as different from the original version.
 *
 * 5. It is Declined to grant rights under trademark law for use of some trade
 *   names, trademarks, or service marks.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program (lgpl.txt).  If not, see <http://www.gnu.org/licenses/>
*/

package es.ants.felixgm.trmsim_wsn.gui.parameterpanels.lftm;

import es.ants.felixgm.trmsim_wsn.gui.parameterpanels.TRMParametersPanel;
import es.ants.felixgm.trmsim_wsn.trm.TRMParameters;
import es.ants.felixgm.trmsim_wsn.trm.lftm.LFTM_Parameters;
import es.ants.felixgm.trmsim_wsn.trm.libs.fuzzylib.FuzzySetPanel;
import es.ants.felixgm.trmsim_wsn.trm.libs.fuzzylib.LinguisticTerm;
import java.util.Collection;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.InputVerifier;

/**
 * <p>This class represents the panel used to retrieve the parameters of LFTM</p>
 * @author <a href="http://ants.dif.um.es/~felixgm/en" target="_blank">F&eacute;lix G&oacute;mez M&aacute;rmol</a>, <a href="http://webs.um.es/gregorio" target="_blank">Gregorio Mart&iacute;nez P&eacute;rez</a>
 * @version 0.5
 * @since 0.4
 */
public class LFTM_ParametersPanel extends TRMParametersPanel {

    protected Vector<DefaultComboBoxModel> membershipFunctionsComboBoxModels;
    protected InputVerifier doubleInputVerifier;
    protected FuzzySetPanel fuzzySetPanelAux, fuzzySetPanel;

    /** Creates new form LFTM_ParametersPanel */
    public LFTM_ParametersPanel() {
        membershipFunctionsComboBoxModels = LFTMPanelSupport.createMembershipFunctionModels(5);
        doubleInputVerifier = LFTMPanelSupport.createDoubleInputVerifier();
        fuzzySetPanelAux = LFTMPanelSupport.createEmptyFuzzySetPanel();
        fuzzySetPanel = LFTMPanelSupport.createEmptyFuzzySetPanel();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        LFTMPanelComponentInitializer.initialize(this);
    }
    // </editor-fold>//GEN-END:initComponents
    void phiSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_phiSliderStateChanged
        LFTMPanelScalarSupport.syncSliderText(phiSlider, phiTextField);
}//GEN-LAST:event_phiSliderStateChanged
    void rhoSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rhoSliderStateChanged
        LFTMPanelScalarSupport.syncSliderText(rhoSlider, rhoTextField);
}//GEN-LAST:event_rhoSliderStateChanged
    void q0SliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_q0SliderStateChanged
        LFTMPanelScalarSupport.syncSliderText(q0Slider, q0TextField);
}//GEN-LAST:event_q0SliderStateChanged
    void numAntsSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numAntsSliderStateChanged
        LFTMPanelScalarSupport.syncSliderText(numAntsSlider, numAntsTextField);
}//GEN-LAST:event_numAntsSliderStateChanged
    void numIterationsSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numIterationsSliderStateChanged
        LFTMPanelScalarSupport.syncSliderText(numIterationsSlider, numIterationsTextField);
}//GEN-LAST:event_numIterationsSliderStateChanged
    void alphaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_alphaSliderStateChanged
        LFTMPanelScalarSupport.syncSliderText(alphaSlider, alphaTextField);
}//GEN-LAST:event_alphaSliderStateChanged
    void betaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_betaSliderStateChanged
        LFTMPanelScalarSupport.syncSliderText(betaSlider, betaTextField);
}//GEN-LAST:event_betaSliderStateChanged
    void initialPheromoneSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_initialPheromoneSliderStateChanged
        LFTMPanelScalarSupport.syncSliderText(initialPheromoneSlider, initialPheromoneTextField);
}//GEN-LAST:event_initialPheromoneSliderStateChanged
    void punishmentThresholdSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_punishmentThresholdSliderStateChanged
        LFTMPanelScalarSupport.syncSliderText(punishmentThresholdSlider, punishmentThresholdTextField);
}//GEN-LAST:event_punishmentThresholdSliderStateChanged
    void pathLengthFactorSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pathLengthFactorSliderStateChanged
        LFTMPanelScalarSupport.syncSliderText(pathLengthFactorSlider, pathLengthFactorTextField);
}//GEN-LAST:event_pathLengthFactorSliderStateChanged
    void transitionThresholdSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_transitionThresholdSliderStateChanged
        LFTMPanelScalarSupport.syncSliderText(transitionThresholdSlider, transitionThresholdTextField);
}//GEN-LAST:event_transitionThresholdSliderStateChanged
    void veryHighMembershipFunctionComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_veryHighMembershipFunctionComboBoxItemStateChanged
        LFTMPanelScalarSupport.updateTrapezoidalVisibility(veryHighMembershipFunctionComboBox, veryHighDParameterTextField);
    }//GEN-LAST:event_veryHighMembershipFunctionComboBoxItemStateChanged
    void highMembershipFunctionComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_highMembershipFunctionComboBoxItemStateChanged
        LFTMPanelScalarSupport.updateTrapezoidalVisibility(highMembershipFunctionComboBox, highDParameterTextField);
    }//GEN-LAST:event_highMembershipFunctionComboBoxItemStateChanged
    void mediumMembershipFunctionComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mediumMembershipFunctionComboBoxItemStateChanged
        LFTMPanelScalarSupport.updateTrapezoidalVisibility(mediumMembershipFunctionComboBox, mediumDParameterTextField);
    }//GEN-LAST:event_mediumMembershipFunctionComboBoxItemStateChanged
    void lowMembershipFunctionComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lowMembershipFunctionComboBoxItemStateChanged
        LFTMPanelScalarSupport.updateTrapezoidalVisibility(lowMembershipFunctionComboBox, lowDParameterTextField);
    }//GEN-LAST:event_lowMembershipFunctionComboBoxItemStateChanged
    void veryLowMembershipFunctionComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_veryLowMembershipFunctionComboBoxItemStateChanged
        LFTMPanelScalarSupport.updateTrapezoidalVisibility(veryLowMembershipFunctionComboBox, veryLowDParameterTextField);
    }//GEN-LAST:event_veryLowMembershipFunctionComboBoxItemStateChanged

    /**
     * Retrieves phi parameter from its corresponding field in the panel
     * @return phi parameter
     */
    protected double get_phi() {
        return LFTMPanelScalarSupport.readDouble(phiTextField);
    }

    /**
     * Sets phi parameter into its corresponding field in the panel
     * @param phi phi parameter value to be set
     */
    protected void set_phi(double phi) {
        LFTMPanelScalarSupport.applySliderValue(phiSlider, phi);
    }

    /**
     * Retrieves rho parameter from its corresponding field in the panel
     * @return rho parameter
     */
    protected double get_rho() {
        return LFTMPanelScalarSupport.readDouble(rhoTextField);
    }

    /**
     * Sets rho parameter into its corresponding field in the panel
     * @param rho rho parameter value to be set
     */
    protected void set_rho(double rho) {
        LFTMPanelScalarSupport.applySliderValue(rhoSlider, rho);
    }

    /**
     * Retrieves q0 parameter from its corresponding field in the panel
     * @return q0 parameter
     */
    protected double get_q0() {
        return LFTMPanelScalarSupport.readDouble(q0TextField);
    }

    /**
     * Sets q0 parameter into its corresponding field in the panel
     * @param q0 q0 parameter value to be set
     */
    protected void set_q0(double q0) {
        LFTMPanelScalarSupport.applySliderValue(q0Slider, q0);
    }

    /**
     * Retrieves numAnts parameter from its corresponding field in the panel
     * @return numAnts parameter
     */
    protected double get_numAnts() {
        return LFTMPanelScalarSupport.readDouble(numAntsTextField);
    }

    /**
     * Sets numAnts parameter into its corresponding field in the panel
     * @param numAnts numAnts parameter value to be set
     */
    protected void set_numAnts(double numAnts) {
        LFTMPanelScalarSupport.applySliderValue(numAntsSlider, numAnts);
    }

    /**
     * Retrieves numIterations parameter from its corresponding field in the panel
     * @return numIterations parameter
     */
    protected double get_numIterations() {
        return LFTMPanelScalarSupport.readDouble(numIterationsTextField);
    }

    /**
     * Sets numIterations parameter into its corresponding field in the panel
     * @param numIterations numIterations parameter value to be set
     */
    protected void set_numIterations(double numIterations) {
        LFTMPanelScalarSupport.applySliderValue(numIterationsSlider, numIterations);
    }

    /**
     * Retrieves alpha parameter from its corresponding field in the panel
     * @return alpha parameter
     */
    protected double get_alpha() {
        return LFTMPanelScalarSupport.readDouble(alphaTextField);
    }

    /**
     * Sets alpha parameter into its corresponding field in the panel
     * @param alpha alpha parameter value to be set
     */
    protected void set_alpha(double alpha) {
        LFTMPanelScalarSupport.applySliderValue(alphaSlider, alpha);
    }

    /**
     * Retrieves beta parameter from its corresponding field in the panel
     * @return beta parameter
     */
    protected double get_beta() {
        return LFTMPanelScalarSupport.readDouble(betaTextField);
    }

    /**
     * Sets beta parameter into its corresponding field in the panel
     * @param beta beta parameter value to be set
     */
    protected void set_beta(double beta) {
        LFTMPanelScalarSupport.applySliderValue(betaSlider, beta);
    }

    /**
     * Retrieves initialPheromone parameter from its corresponding field in the panel
     * @return initialPheromone parameter
     */
    protected double get_initialPheromone() {
        return LFTMPanelScalarSupport.readDouble(initialPheromoneTextField);
    }

    /**
     * Sets initialPheromone parameter into its corresponding field in the panel
     * @param initialPheromone initialPheromone parameter value to be set
     */
    protected void set_initialPheromone(double initialPheromone) {
        LFTMPanelScalarSupport.applySliderValue(initialPheromoneSlider, initialPheromone);
    }

    /**
     * Retrieves transitionThreshold parameter from its corresponding field in the panel
     * @return transitionThreshold parameter
     */
    protected double get_transitionThreshold() {
        return LFTMPanelScalarSupport.readDouble(transitionThresholdTextField);
    }

    /**
     * Sets transitionThreshold parameter into its corresponding field in the panel
     * @param transitionThreshold transitionThreshold parameter value to be set
     */
    protected void set_transitionThreshold(double transitionThreshold) {
        LFTMPanelScalarSupport.applySliderValue(transitionThresholdSlider, transitionThreshold);
    }

    /**
     * Retrieves pathLengthFactor parameter from its corresponding field in the panel
     * @return pathLengthFactor parameter
     */
    protected double get_pathLengthFactor() {
        return LFTMPanelScalarSupport.readDouble(pathLengthFactorTextField);
    }

    /**
     * Sets pathLengthFactor parameter into its corresponding field in the panel
     * @param pathLengthFactor pathLengthFactor parameter value to be set
     */
    protected void set_pathLengthFactor(double pathLengthFactor) {
        LFTMPanelScalarSupport.applySliderValue(pathLengthFactorSlider, pathLengthFactor);
    }

    /**
     * Retrieves punishmentThreshold parameter from its corresponding field in the panel
     * @return punishmentThreshold parameter
     */
    protected double get_punishmentThreshold() {
        return LFTMPanelScalarSupport.readDouble(punishmentThresholdTextField);
    }

    /**
     * Sets punishmentThreshold parameter into its corresponding field in the panel
     * @param punishmentThreshold punishmentThreshold parameter value to be set
     */
    protected void set_punishmentThreshold(double punishmentThreshold) {
        LFTMPanelScalarSupport.applySliderValue(punishmentThresholdSlider, punishmentThreshold);
    }

    /**
     * Retrieves U_MIN parameter from its corresponding field in the panel
     * @return U_MIN parameter
     */
    protected double get_U_MIN() {
        return LFTMPanelScalarSupport.readDouble(universeMINTextField);
    }

    /**
     * Sets U_MIN parameter into its corresponding field in the panel
     * @param U_MIN U_MIN parameter value to be set
     */
    protected void set_U_MIN(double U_MIN) {
        LFTMPanelScalarSupport.applyTextValue(universeMINTextField, U_MIN);
    }

    /**
     * Retrieves U_MAX parameter from its corresponding field in the panel
     * @return U_MAX parameter
     */
    protected double get_U_MAX() {
        return LFTMPanelScalarSupport.readDouble(universeMAXTextField);
    }

    /**
     * Sets U_MAX parameter into its corresponding field in the panel
     * @param U_MAX U_MAX parameter value to be set
     */
    protected void set_U_MAX(double U_MAX) {
        LFTMPanelScalarSupport.applyTextValue(universeMAXTextField, U_MAX);
    }

    /**
     * Retrieves linguisticTerms parameter from its corresponding fields in the panel
     * @return linguisticTerms parameter
     */
    protected Collection<LinguisticTerm> getLinguisticTerms() {
        return LFTMPanelLinguisticTermsSupport.readTerms(
                get_U_MIN(),
                get_U_MAX(),
                new javax.swing.JComboBox[] {
                        veryHighMembershipFunctionComboBox,
                        highMembershipFunctionComboBox,
                        mediumMembershipFunctionComboBox,
                        lowMembershipFunctionComboBox,
                        veryLowMembershipFunctionComboBox
                },
                new javax.swing.JTextField[][] {
                        {veryHighAParameterTextField, veryHighBParameterTextField, veryHighCParameterTextField, veryHighDParameterTextField},
                        {highAParameterTextField, highBParameterTextField, highCParameterTextField, highDParameterTextField},
                        {mediumAParameterTextField, mediumBParameterTextField, mediumCParameterTextField, mediumDParameterTextField},
                        {lowAParameterTextField, lowBParameterTextField, lowCParameterTextField, lowDParameterTextField},
                        {veryLowAParameterTextField, veryLowBParameterTextField, veryLowCParameterTextField, veryLowDParameterTextField}
                });
    }

    /**
     * Sets linguisticTerms parameter into its corresponding fields in the panel
     * @param linguisticTerms linguisticTerms parameter value to be set
     */
    protected void set_LinguisticTerms(Collection<LinguisticTerm> linguisticTerms) {
        fuzzySetPanel = LFTMPanelLinguisticTermsSupport.applyTerms(
                linguisticTerms,
                new javax.swing.JComboBox[] {
                        veryHighMembershipFunctionComboBox,
                        highMembershipFunctionComboBox,
                        mediumMembershipFunctionComboBox,
                        lowMembershipFunctionComboBox,
                        veryLowMembershipFunctionComboBox
                },
                new javax.swing.JTextField[][] {
                        {veryHighAParameterTextField, veryHighBParameterTextField, veryHighCParameterTextField, veryHighDParameterTextField},
                        {highAParameterTextField, highBParameterTextField, highCParameterTextField, highDParameterTextField},
                        {mediumAParameterTextField, mediumBParameterTextField, mediumCParameterTextField, mediumDParameterTextField},
                        {lowAParameterTextField, lowBParameterTextField, lowCParameterTextField, lowDParameterTextField},
                        {veryLowAParameterTextField, veryLowBParameterTextField, veryLowCParameterTextField, veryLowDParameterTextField}
                },
                linguisticTermsPanel,
                linguisticTermsPanelContainer);
        fuzzySetPanelAux = fuzzySetPanel;
        linguisticTermsPanelContainer = fuzzySetPanelAux;
    }

    @Override
    public TRMParameters get_TRMParameters() {
        LFTM_Parameters lftmParameters = new LFTM_Parameters();
        LFTMPanelParametersMapper.copyPanelToParameters(this, lftmParameters);
        return lftmParameters;
    }

    @Override
    public void set_TRMParameters(TRMParameters trmParameters) {
        LFTM_Parameters lftmParameters = (LFTM_Parameters)trmParameters;
        LFTMPanelParametersMapper.copyParametersToPanel(lftmParameters, this);
    }

    @Override
    public void setEnabled(boolean enabled) {
        LFTMPanelScalarSupport.setEnabled(enabled,
                phiLabel, phiSlider, rhoLabel, rhoSlider, q0Label, q0Slider,
                numAntsLabel, numAntsSlider, numIterationsLabel, numIterationsSlider,
                alphaLabel, alphaSlider, betaLabel, betaSlider,
                initialPheromoneLabel, initialPheromoneSlider,
                transitionThresholdLabel, transitionThresholdSlider,
                pathLengthFactorLabel, pathLengthFactorSlider,
                punishmentThresholdLabel, punishmentThresholdSlider,
                membershipFunctionLabel, aParameterLabel, bParameterLabel, cParameterLabel, dParameterLabel,
                veryHighLabel, veryHighMembershipFunctionComboBox, veryHighAParameterTextField, veryHighBParameterTextField, veryHighCParameterTextField, veryHighDParameterTextField,
                highLabel, highMembershipFunctionComboBox, highAParameterTextField, highBParameterTextField, highCParameterTextField, highDParameterTextField,
                mediumLabel, mediumMembershipFunctionComboBox, mediumAParameterTextField, mediumBParameterTextField, mediumCParameterTextField, mediumDParameterTextField,
                lowLabel, lowMembershipFunctionComboBox, lowAParameterTextField, lowBParameterTextField, lowCParameterTextField, lowDParameterTextField,
                veryLowLabel, veryLowMembershipFunctionComboBox, veryLowAParameterTextField, veryLowBParameterTextField, veryLowCParameterTextField, veryLowDParameterTextField,
                universeMINLabel, universeMINTextField, universeMAXLabel, universeMAXTextField,
                linguisticTermsPanelContainer, fuzzySetPanelAux, fuzzySetPanel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel aParameterLabel;
    javax.swing.JLabel alphaLabel;
    javax.swing.JSlider alphaSlider;
    javax.swing.JTextField alphaTextField;
    javax.swing.JLabel bParameterLabel;
    javax.swing.JLabel betaLabel;
    javax.swing.JSlider betaSlider;
    javax.swing.JTextField betaTextField;
    javax.swing.JPanel btrm_ParametersPanel;
    javax.swing.JLabel cParameterLabel;
    javax.swing.JLabel dParameterLabel;
    javax.swing.JTextField highAParameterTextField;
    javax.swing.JTextField highBParameterTextField;
    javax.swing.JTextField highCParameterTextField;
    javax.swing.JTextField highDParameterTextField;
    javax.swing.JLabel highLabel;
    javax.swing.JComboBox highMembershipFunctionComboBox;
    javax.swing.JLabel initialPheromoneLabel;
    javax.swing.JSlider initialPheromoneSlider;
    javax.swing.JTextField initialPheromoneTextField;
    javax.swing.JTabbedPane lftm_ParametersPanelTabbedPane;
    javax.swing.JPanel linguisticTermsPanel;
    javax.swing.JPanel linguisticTermsPanelContainer;
    javax.swing.JTextField lowAParameterTextField;
    javax.swing.JTextField lowBParameterTextField;
    javax.swing.JTextField lowCParameterTextField;
    javax.swing.JTextField lowDParameterTextField;
    javax.swing.JLabel lowLabel;
    javax.swing.JComboBox lowMembershipFunctionComboBox;
    javax.swing.JTextField mediumAParameterTextField;
    javax.swing.JTextField mediumBParameterTextField;
    javax.swing.JTextField mediumCParameterTextField;
    javax.swing.JTextField mediumDParameterTextField;
    javax.swing.JLabel mediumLabel;
    javax.swing.JComboBox mediumMembershipFunctionComboBox;
    javax.swing.JLabel membershipFunctionLabel;
    javax.swing.JLabel numAntsLabel;
    javax.swing.JSlider numAntsSlider;
    javax.swing.JTextField numAntsTextField;
    javax.swing.JLabel numIterationsLabel;
    javax.swing.JSlider numIterationsSlider;
    javax.swing.JTextField numIterationsTextField;
    javax.swing.JLabel pathLengthFactorLabel;
    javax.swing.JSlider pathLengthFactorSlider;
    javax.swing.JTextField pathLengthFactorTextField;
    javax.swing.JLabel phiLabel;
    javax.swing.JSlider phiSlider;
    javax.swing.JTextField phiTextField;
    javax.swing.JLabel punishmentThresholdLabel;
    javax.swing.JSlider punishmentThresholdSlider;
    javax.swing.JTextField punishmentThresholdTextField;
    javax.swing.JLabel q0Label;
    javax.swing.JSlider q0Slider;
    javax.swing.JTextField q0TextField;
    javax.swing.JLabel rhoLabel;
    javax.swing.JSlider rhoSlider;
    javax.swing.JTextField rhoTextField;
    javax.swing.JLabel transitionThresholdLabel;
    javax.swing.JSlider transitionThresholdSlider;
    javax.swing.JTextField transitionThresholdTextField;
    javax.swing.JLabel universeMAXLabel;
    javax.swing.JTextField universeMAXTextField;
    javax.swing.JLabel universeMINLabel;
    javax.swing.JTextField universeMINTextField;
    javax.swing.JTextField veryHighAParameterTextField;
    javax.swing.JTextField veryHighBParameterTextField;
    javax.swing.JTextField veryHighCParameterTextField;
    javax.swing.JTextField veryHighDParameterTextField;
    javax.swing.JLabel veryHighLabel;
    javax.swing.JComboBox veryHighMembershipFunctionComboBox;
    javax.swing.JTextField veryLowAParameterTextField;
    javax.swing.JTextField veryLowBParameterTextField;
    javax.swing.JTextField veryLowCParameterTextField;
    javax.swing.JTextField veryLowDParameterTextField;
    javax.swing.JLabel veryLowLabel;
    javax.swing.JComboBox veryLowMembershipFunctionComboBox;
    // End of variables declaration//GEN-END:variables
}
